env_cfg:
  num_actions: 4
  max_throttle: 1.0
  max_roll_rate: 15.0
  max_pitch_rate: 15.0 
  max_yaw_rate: 5.0

  # termination
  termination_if_roll_greater_than: 180  # degree
  termination_if_pitch_greater_than: 180
  termination_if_close_to_ground: 0.1
  termination_if_x_greater_than: 3.0
  termination_if_y_greater_than: 3.0
  termination_if_z_greater_than: 2.0
  termination_cable_angle_threshold: 1.571

  base_init_pos: [0.0, 0.0, 1.0]
  base_init_quat: [1.0, 0.0, 0.0, 0.0]
  episode_length_s: 15.0
  at_target_threshold: 0.5
  resampling_time_s: 3.0
  simulate_action_latency: True
  clip_actions: 1.0
  cable_length: 0.48
  num_of_dofs: 63
  max_safety_violations: 150
  max_safe_cable_angle_deg: 75
  visualize_target: False 
  visualize_camera: False 
  max_visualize_FPS: 60 
  TWR_max: 3.5

obs_cfg: 
  num_obs: 26
  obs_scales:
    rel_pos_xy: 0.3333333333333333
    rel_pos_z: 1.0
    lin_vel_xy: 0.1
    lin_vel_z: 0.3
    ang_vel_yaw: 0.3183098861837907
    cable_angle: 0.66666667
    cable_angle_vel: 0.1 

reward_cfg:
  yaw_lambda: -10.0 
  reward_scales:
    target: 10.0 
    smooth: -0.0001 
    yaw: 0.01 
    angular: -0.0002
    crash: -10.0
    cable_angle_safety: 0.03
  unsafe_angle_penalty: 1.0

command_cfg:
  num_commands: 3 
  pos_x_range: [-1.5, 1.5] 
  pos_y_range: [-1.5, 1.5]
  pos_z_range: [0.5, 1.5] 
